#---
spring.config.activate.on-profile = production

# Default datasource credentials configuration.
spring.datasource.username = ${SPRING_DATASOURCE_USERNAME}
spring.datasource.password = ${SPRING_DATASOURCE_PASSWORD}
spring.datasource.url = ${SPRING_DATASOURCE_URL}

# Hibernate configuration.
spring.datasource.driver-class-name = com.p6spy.engine.spy.P6SpyDriver

# Logging
logging.level.root = INFO
logging.file.name = ./logs/app.log

# Server configuration.
server.port = 8080

# Application specific configuration.
app.jwtExpirationMs = ${JWT_EXPIRATION_MS:#{2592000}}
app.jwtSecret = ${JWT_SECRET}

# Flyway migration configuration.
spring.flyway.locations=classpath:db/migration
spring.flyway.validateMigrationNaming = true
spring.flyway.baselineOnMigrate = true
spring.jpa.hibernate.ddl-auto = none
spring.flyway.enabled = true

# Email configuration
spring.mail.host = ${SMTP_HOST}
spring.mail.port = ${SMTP_PORT}
spring.mail.username = ${SMTP_USERNAME}
spring.mail.password = ${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

app.aesSecretKey = ${APP_AES_SECRET_KEY}
app.url = ${APP_URL}

# Sentry configuration
sentry.use-git-commit-id-as-release = false
sentry.traces-sample-rate = 0.2
sentry.send-default-pii = true
sentry.logs.enabled = true
sentry.sample-rate = 0.2

sentry.environment = production
sentry.dsn = ${SENTRY_DSN}

#---
spring.config.activate.on-profile = local

# Default datasource credentials configuration.
spring.datasource.username = ${SPRING_DATASOURCE_USERNAME}
spring.datasource.password = ${SPRING_DATASOURCE_PASSWORD}
spring.datasource.url = ${SPRING_DATASOURCE_URL}

# Hibernate configuration.
spring.datasource.driver-class-name = com.p6spy.engine.spy.P6SpyDriver
spring.jpa.show-sql = true

# Logging
logging.level.root = INFO
logging.file.name = ./logs/app.log

# Server configuration.
server.port = 8080

# Application specific configuration.
app.jwtExpirationMs = ${JWT_EXPIRATION_MS:#{2592000}}
app.jwtSecret = ${JWT_SECRET}

# Flyway migration configuration.
spring.flyway.locations=classpath:db/migration
spring.flyway.validateMigrationNaming = true
spring.flyway.baselineOnMigrate = true
spring.jpa.hibernate.ddl-auto = none
spring.flyway.enabled = true

# Email configuration
spring.mail.host = ${SMTP_HOST}
spring.mail.port = ${SMTP_PORT}
spring.mail.username = ${SMTP_USERNAME}
spring.mail.password = ${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

app.aesSecretKey = ${APP_AES_SECRET_KEY}
app.url = ${APP_URL}

# Sentry configuration
sentry.use-git-commit-id-as-release = false
sentry.traces-sample-rate = 1.0
sentry.send-default-pii = true
sentry.sample-rate = 1

sentry.environment = local
sentry.dsn = ${SENTRY_DSN}

#---
spring.config.activate.on-profile = test

# Default datasource credentials configuration.
spring.datasource.username = ${SPRING_TEST_DATASOURCE_USERNAME}
spring.datasource.password = ${SPRING_TEST_DATASOURCE_PASSWORD}
spring.datasource.url = ${SPRING_TEST_DATASOURCE_URL}


# Hibernate configuration.
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Server configuration.
server.port = 8080

# Application specific configuration.
app.jwtExpirationMs = ${JWT_TEST_EXPIRATION_MS:#{2592000}}
app.jwtSecret = ${JWT_TEST_SECRET}

# Flyway migration configuration.
spring.flyway.baselineOnMigrate = true
spring.flyway.enabled = false
